### ISSUE TITLE
Updated GUI animations

### ISSUE THREAD

**Issue by garyjacobs** [chrissimpkins/Crunch#39] opened 2018-05-17 05:19 UTC
Here are some updated animations for the GUI version of "Drag and Drop"

There are 5 states outlined as follows:

**01-Load-Up.gif**
This should play once and then switch to "Waiting"

**02-Waiting.gif**
This will loop and wait until the user places file(s) onto the GUI window

**03-Crunching.gif**
This will loop while the magic is happening

**04-Error.gif**
This will play once when something went Wrong (error)

**04-Success.gif**
This will play once when the compression is complete and state in view for 1-2 secs then reset back to  "Waiting GIF".

Dimensions of animations are 600x300 - these would look best filling the entire container it sits in.

Open to suggestions on wording and visuals displayed here.

![01-load-up](https://user-images.githubusercontent.com/38194997/40210128-9930d96e-5a86-11e8-8665-da03849e17ee.gif)
![02-waiting](https://user-images.githubusercontent.com/38194997/40210129-9965b616-5a86-11e8-9089-42caaf486711.gif)
![03-crunching](https://user-images.githubusercontent.com/38194997/40210130-999aa60a-5a86-11e8-8750-81e48f6f85f7.gif)
![04-error](https://user-images.githubusercontent.com/38194997/40210132-99ce79a8-5a86-11e8-9a68-0b849f058fc2.gif)
![04-success](https://user-images.githubusercontent.com/38194997/40210133-9a01c100-5a86-11e8-8ee0-6561766a0a56.gif)

---
@chrissimpkins edits below:

TODO:

- [x] window size increase vs. image size decrease (vs. existing window design) - keep existing size
- [x] decide license for these images - MIT license, no change https://github.com/chrissimpkins/Crunch/issues/39#issuecomment-390059082
- [x] submit PR with images placed in `img` directory
- [x] update animations in Crunch macOS GUI tool
- [x] release the new success/failure status indicator animations with new logging of failures (#37)
- [x] update About window text with acknowledgment
- [x] update README documentation with acknowledgment
- [x] update [macOS GUI Usage documentation](https://github.com/chrissimpkins/Crunch/blob/master/docs/MACOSGUI.md#usage) animated gif image with new design

**Comment by garyjacobs** [comment] 2018-05-17 05:34
Thanks for putting me onto this GEM that has become a part of our workflow in less that a day. 👍

**Comment by albinekb** [comment] 2018-05-17 13:30
Awesome animations! I got an idea for potential improvement:

Add thumbs up 👍 on success and 👎 on fail? 😄

**Comment by badcat** [comment] 2018-05-17 14:17
Love these animations - no if only the app was called **Punch!** or **Scrunch** or something other thatnCrunch, since makes me think of this Crunch - https://getcrunch.co which is by its own admission is, "Faster, Tastier and Crunchier"  :)

**Comment by garyjacobs** [comment] 2018-05-18 00:49
Hey @chrissimpkins 

I've updated the fists in the animation to be more like a mechanical vice for crunching machine.
In terms of license - Which ever option sees the user reading less licence agreements honestly. So I'm cool with the MIT one or which ever is easiest to implement. I'm not precious about it.

**GUI Window Size**

I've taken a screenshot of GUI and deduced from that screenshot that the inner window size is 400 x 200. You will need to cater for HDPI (Retina/5K) screen resolutions, so I've created an @1x (400x200) version and also @2x version )800x400 which should render sharper for HDPI screens.

If there is no option to specify two sets of images - just use the @2x onesto cover off the HDPI resolution and set the image size to be 400x200.

I'll see if I can get these into a PR now.

**Comment by chrissimpkins** [comment] 2018-05-18 14:10
Updates look great!

> Which ever option sees the user reading less licence agreements honestly. So I'm cool with the MIT one or which ever is easiest to implement.

Will not modify the existing licenses to address the new images based upon your response.


> I think keep the size of the window you have and I'll update the artwork dimensions.
I've taken a screenshot of GUI and deduced from that screenshot that the inner window size is 400x200. You will need to cater for HDPI (Retina/5K) screen resolutions, so I've created a @1x (400x200) version and also a @2x version (800x400) which should render sharper for the HDPI screens.

Beginning work on this over the next week.  I've tentatively slated the work here as part of a new major release (v3.0.0) which will include an updated version of zopflipng.  I need to explore the zopflipng change a bit. The commit logs suggest there could be compression gains.  

> added the image to a PR

#43 👍

**Comment by chrissimpkins** [comment] 2018-05-22 01:10
images merged to dev branch.  starting work on the animation updates

**Comment by chrissimpkins** [comment] 2018-05-23 22:07
Gary, animations are looking great!  I started on the application open transition between images 01 and 02.  Here is where we currently are:

![n5911-video](https://user-images.githubusercontent.com/4249591/40453454-3c35f5ba-5eb3-11e8-87f1-8d7bb26ed971.gif)

I am having a difficult time with the timing of the transition in the dashed lines that circle around the middle circle between images 01 and 02.  Note the slight jump in position of the lines in the two images.  I've tried transitions at 0.5 - 1.1 sec.  It looks best in the 0.5 - 0.9sec range.  When I get to 1 sec and above there is a visually apparent transition between the entire image.  I don't know why it occurs.  Thoughts about simply removing the dashed lines in image 01 and either fading in or just letting them appear and begin animating in a circular fashion at image 02?

The other issue is that there seems to be a 5'ish (or maybe 10) px border around the image that is not specified in CSS.  I have the background of the HTML set to the background color of the images.   Thoughts about adding a border around the images that is the same color as the light grey window color?

I'd be happy to build a copy of the application that you can view if you'd like to take a look.

**Comment by garyjacobs** [comment] 2018-05-24 03:13
Hmmm... Yeah the timings seem a bit off. 
Do you have to put in the timings of when they GIF's swap out?

If yes, there are a couple of options here:

1) I can extend the GIF duration to be a round 2 seconds and then when you swap from one gif to the next it should be seamless?

2) I can find out the exact timing of first animation end and you set it to that?

Or yes- I can remove the dashed line in the first load up screen but the mechanical arms coming in are not as smooth as they should be - It seems like something in being cut short.

<img width="585" alt="screen shot 2018-05-24 at 12 39 08 pm" src="https://user-images.githubusercontent.com/38194997/40461612-8746b2e6-5f4f-11e8-9d8d-b80357b3de1c.png">

**Comment by chrissimpkins** [comment] 2018-05-24 03:44
I put all of the animations together from start to success and fail.  It looks great.  My suggestion is to simply combine images 01 and 02 into a single image if possible.  The current animation stitching is as follows:

Application open : Image 01 --> Image 02 then wait

Execution to success: Image 03 ---> Image 04-Success ---> Image 01 --> Image 02 then wait

Execution to fail: Image 03 ---> Image 04-Fail ---> Image 01 --> Image 02 then wait

Everything looks great except the transition between 01 --> 02.  If those are combined into one image I think the issue is solved.  Give me a few mins and I will build and push a copy that you can try so that you can see what I mean.

**Comment by chrissimpkins** [comment] 2018-05-24 03:53
Here is an installer so that you can have a look at the current timings across the images:

[Crunch-installer.zip](https://github.com/chrissimpkins/Crunch/files/2033751/Crunch-installer.zip)

**Comment by chrissimpkins** [comment] 2018-05-24 03:54
That should show up as v3.0.0-dev1 in the About window

**Comment by garyjacobs** [comment] 2018-05-24 05:18
Yeah I can see the jump. Why not just remove Image 01 and just use Image 02 as loading/waiting. 
P.S. - It's looking good!

**Comment by chrissimpkins** [comment] 2018-05-24 11:19
@garyjacobs OK sounds good.  Will eliminate 01 altogether.

**Comment by chrissimpkins** [comment] 2018-05-24 11:57
Anyone have thoughts about the duration of the success and error image display before the transition back to the wait animation? Currently at 2 sec.  Too short? Too long?

**Comment by chrissimpkins** [comment] 2018-05-24 12:02
To view the fail screen, drop any non png file on the window.

**Comment by chrissimpkins** [comment] 2018-05-25 03:02
The animations were updated with revised transition timings and I am pretty happy with how all of these new animations appear at this stage.  I really like the opening animation and decided to keep it despite the minor shift in the dashed lines around the circle.  

For those who want to check it out with the brand new animations that Gary contributed, here is a new installer that will show as v3.0.0-dev2.  

[installer.zip](https://github.com/chrissimpkins/Crunch/files/2037786/installer.zip)

Let me know if you have any feedback about the timing of the transitions and the current designs. My own opinion is that they look gtg for the next release.  Open to suggestions for further improvements.

We are closing in on the v3.0.0 release and these new animations will be a big part of it.  This looks great Gary.  I really appreciate your efforts here. The About menu was updated with an acknowledgment + link to your Github account and I will add this to the README page as well.

**Comment by chrissimpkins** [comment] 2018-05-31 03:49
Logging of successes (with compression data) / failures (with reason) has been implemented in a build that includes the new animations for successful and failed Crunch macOS GUI execution.  See #58 for installer download details if you are available to test.  The log file path is `$HOME/.crunch/crunch.log`.

**Closed as completed** 2018-06-04 02:21 UTC
Labels: enhancement, macOS GUI
