### ISSUE TITLE
option: Cover the original file 

### ISSUE THREAD

**Issue by bikmanwei** [chrissimpkins/Crunch#64] opened 2018-06-05 14:00 UTC
Hi Crunch team,

Life saving tool!!!
Could you add a function that allow user to cover the original files directly with the crunched files generated? Thank you!

Greetings from Holland.
Bikman

**Comment by chrissimpkins** [comment] 2018-06-05 14:12
Thanks for the very nice comments and for this suggestion!  To confirm, is this a duplicate of the request in #20?  You would like to overwrite the original file path with the optimized image file?

**Comment by bikmanwei** [comment] 2018-06-05 14:17
Yes! Sorry for the re-post! please remove my feedback. Thank you!

**Comment by chrissimpkins** [comment] 2018-06-05 14:22
No worries at all! Let's consolidate conversation there.   Feel free to weigh in with thoughts about an approach for the tool that you are using.  I am limited in ability to support a preferences window in the GUI application but we can make it happen with another approach.

**Closed by chrissimpkins** 2018-06-05 14:22 UTC
