### ISSUE TITLE
macOS 12.3.1+: error during GUI application execution

### ISSUE THREAD

**Issue by dev-coco** [chrissimpkins/Crunch#92] opened 2022-06-06 02:52 UTC
**Describe the bug**
Drag any image into the prompt: hmmm. Looks like something didn't work.

**To Reproduce**
1. Open 'application...'
2. Do 'Drag any image...'
3. I see 'hmmm. Looks like something didn't work....'

**Expected behavior**
hmmm. Looks like something didn't work.

**Screenshots and/or Log Text**
There is no such file in this directory. `~/.crunch/crunch.log`

**Desktop (please complete the following information):**
 - macOS
 - 12.3.1

**Additional context**
I have confirmed that the image I dragged in is in png format, but it still doesn't work.

---

### Maintainer edits

- Test fix 1 is available in https://github.com/chrissimpkins/Crunch/issues/92#issuecomment-1152951156

**Comment by chrissimpkins** [comment] 2022-06-06 16:08
What installation approach did you use?

**Comment by masey9** [comment] 2022-06-06 22:14
Yeah same for me. Stopped working for PNGs for me about 3 weeks ago. 

Now I just get the ol' "Looks like something didn't work." message.

- Running v4.0.0 (1)
- macOS 12.4

<img width="542" alt="CleanShot 2022-06-07 at 08 11 47@2x" src="https://user-images.githubusercontent.com/1266692/172257965-4e3df578-d2d5-44f3-8bcb-8903795ae035.png">
<img width="326" alt="CleanShot 2022-06-07 at 08 12 11@2x" src="https://user-images.githubusercontent.com/1266692/172257984-7bbf8e4e-4831-4ff6-b185-ee1dfcda909c.png">
<img width="291" alt="CleanShot 2022-06-07 at 08 13 46@2x" src="https://user-images.githubusercontent.com/1266692/172258034-1e5816f6-b61d-41d1-a2e3-a2be6781ba84.png">

**Comment by dev-coco** [comment] 2022-06-10 19:43
Can this problem be fixed?

**Comment by chrissimpkins** [comment] 2022-06-10 19:47
Will try to have a look into it this weekend.  Will let you know asap!

**Comment by chrissimpkins** [comment] 2022-06-10 19:51
My guess is that some default file write permissions settings changed in a recent macOS release.  If necessary, we can bag the log file if that is the source.  Or move it to a directory with default write permissions if that is possible.  Unclear if I can make that happen with the approach that we use here to prep the GUI.  Let's see.

**Comment by chrissimpkins** [comment] 2022-06-10 19:56
I can reproduce on macOS 12.4. Will be in touch as soon as I know more.

**Comment by chrissimpkins** [comment] 2022-06-11 14:36
Can confirm that the command line executable functions without issues using the repository installation instruction on macOS 12.4.  

Diving into the GUI issue.

**Comment by chrissimpkins** [comment] 2022-06-11 15:27
Mind trying again with application that is installed with this installer?  I can confirm that it works in a MacBook Pro (16-inch, 2021) + macOS 12.4 environment.  The application version in the About menu will show as 5.0.0

[Crunch 5.0.0.dmg.zip](https://github.com/chrissimpkins/Crunch/files/8884222/Crunch.5.0.0.dmg.zip)

**Comment by chrissimpkins** [comment] 2022-06-11 15:52
This appears to be the issue https://github.com/chrissimpkins/Crunch/pull/94/commits/bcc675e6d2259c3e2e613378b2e65fbee75beff4

and the fix will lead to #93

**Comment by chrissimpkins** [comment] 2022-06-11 15:54
Once I receive confirmation that this works for you, I'll prep and release v4.0.1 with these changes.

Will rebase #82 on these edits and try to get the v5 release out in short order after.

**Comment by dev-coco** [comment] 2022-06-11 19:20
Nice! 5.0.0 version is work for me!

**Closed** 2022-06-11 21:10 UTC
Labels: bug

**Comment by chrissimpkins** [comment] 2022-06-12 01:11
The fix was released in v5.0.0.  This is the PR if you use homebrew: https://github.com/Homebrew/homebrew-cask/pull/125473. Once that is merged you should be able to install the update with homebrew.

Thank you very much for reporting this issue!

@masey9 please let me know if this did not address your issue.

**Comment by sjml** [comment] 2022-06-12 05:33
@chrissimpkins Thanks for the quick fix! Just curious: what’s your plan for when Apple pulls Python out of the base system? Just tell people to install their own? Package it alongside? Rewrite?

**Comment by masey9** [comment] 2022-06-12 12:12
> @masey9 please let me know if this did not address the problem for you.

Successfully crunched a couple of files again so it looks like we're back in action. Thanks mate!

**Comment by chrissimpkins** [comment] 2022-06-12 14:32
> @chrissimpkins Thanks for the quick fix! Just curious: what’s your plan for when Apple pulls Python out of the base system? Just tell people to install their own? Package it alongside? Rewrite? 

Good question.  This decision will affect a significant number of projects out there.  The answer will likely be a requirement to install Python on macOS for this project.

**Comment by chrissimpkins** [comment] 2022-06-12 14:34
> > @chrissimpkins Thanks for the quick fix! Just curious: what’s your plan for when Apple pulls Python out of the base system? Just tell people to install their own? Package it alongside? Rewrite? 
> 
> Good question.  This decision will affect a significant number of projects out there.  The answer will likely be a requirement to install Python on macOS for this project.
> 
> 

and fwiw, this may not be a bad thing.  macOS system python tends to be years behind the latest Py interpreter release.

**Comment by sjml** [comment] 2022-06-12 14:35
> and fwiw, this may not be a bad thing. macOS system python tends to be years behind the latest Py interpreter release.

Oh, 100% for sure. I was just curious how folks who used Python to make apps were planning to address it going away.

**Comment by chrissimpkins** [comment] 2022-06-12 14:48
> > and fwiw, this may not be a bad thing. macOS system python tends to be years behind the latest Py interpreter release.
> 
> 
> 
> Oh, 100% for sure. I was just curious how folks who used Python to make apps were planning to address it going away. 

IIUC this will affect other langs like Ruby and Perl too.  Warm up the issue trackers.  :)

**Comment by dbrabyn** [comment] 2022-06-12 17:18
I'm getting asked to download the command line developer tools with v5. Wasn't necessary before AFAIK.

**Comment by chrissimpkins** [comment] 2022-06-12 19:26
Yeah I think that Apple dropped python 2 (=`python`).  And Py 3 may be in the Xcode dev/ command line tools.  Will you please let me know what the full installation process is on your system so that we can document it? I don't have a box without multiple versions of python to test this.

**Comment by chrissimpkins** [comment] 2022-06-12 19:27
and what macOS version are you using?

**Comment by dbrabyn** [comment] 2022-06-12 19:46
MacOS 12.4 and using the dmg installer. Is that what you mean by the full installation process?

Here is the prompt I get:
![CleanShot 2022-06-12 at 15 45 35@2x](https://user-images.githubusercontent.com/6307031/173250564-1006f3ea-bc2d-4118-b728-440e4413e27a.jpg)

**Comment by chrissimpkins** [comment] 2022-06-12 19:49
Ty!

Fwiw, you can just install the latest cPy 3 from the Python site.  No need to install the full set of xcode dev tools

**Comment by dbrabyn** [comment] 2022-06-12 20:41
This is very much not my area; I just love my Crunch.

cPy 3 = Python 3.10.5?

**Comment by chrissimpkins** [comment] 2022-06-12 20:55
Apologies! Yes, you can just install the latest Python 3 from the main Python site

https://www.python.org/downloads/

**Comment by dbrabyn** [comment] 2022-06-12 23:31
Still asking me for the CL dev tools after installing Python. Do I need to configure something?

**Comment by chrissimpkins** [comment] 2022-06-13 01:15
What do you see when you enter `/usr/bin/env python3` on the command line?

**Comment by dbrabyn** [comment] 2022-06-13 01:39
`Python 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin`

**Comment by chrissimpkins** [comment] 2022-06-13 01:52
No idea why it would still be prompting you to install the command line tools.  That should be all that you need to use the Python script, including in the GUI. Maybe try a reboot.  If that doesn't do it, it looks like you may be forced to install the command line tools. Sorry!  I don't know why Apple is doing this.

**Comment by dbrabyn** [comment] 2022-06-16 15:35
Using the Service route I get this message. If this helps.

![CleanShot 2022-06-16 at 11 32 24@2x](https://user-images.githubusercontent.com/6307031/174106770-34e25ee8-725b-4ed0-b6fd-d3d3a5993e96.jpg)

**Comment by chrissimpkins** [comment] 2022-06-16 18:00
Interested in contributing this information to our documentation?  I suggest that we let users know that you apparently need to install XCode developer tools on recent versions of macOS.
