### ISSUE TITLE
DMG version - pngquant missing

### ISSUE THREAD

**Issue by TraderStf** [chrissimpkins/Crunch#10] opened 2018-03-26 14:01 UTC
Dyld Error Message:
  Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Applications/Crunch.app/Contents/Resources/./pngquant

**Comment by chrissimpkins** [comment] 2018-03-26 14:16
Thanks for the report! This is a duplicate of the issue report here: https://github.com/chrissimpkins/Crunch/issues/7 

My fault 😲 

I pushed an update to the Homebrew Cask install script last night that should address it for those who install with homebrew.  I suppose that I will make this the recommended approach given these issues and the fact that we can automate the dependency installs.  For dmg installs, I need to update documentation to indicate that these are dependencies for this project so that users can do this manually before use.

Closing this in favor of #7.   Let's continue the conversation there.  On it and fixes in the works!

**Closed by chrissimpkins** 2018-03-26 14:16 UTC
